name: Run Jest Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: app
      run: npm install

    - name: Run Jest tests
      working-directory: app
      run: npm run test

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: jest-test-results
        path: app/test-results/junit/results.xml
