name: Run Jest Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: iot-system-prototype/app
      run: npm install

    - name: Run Jest tests
      working-directory: iot-system-prototype/app
      run: npm run test
